[project]
name = "snakemake-kubernetes-api"
version = "0.1.0"


[tool.pixi.project]
name = "snakemake-kubernetes-api"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
python = "3.12.*"
