name: Semantic Release

on:
  push:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]
  pull_request:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]

jobs:
  Run-A-Pixi-Job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run A Pixi Job
      run: echo "Running a Pixi Job"

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.18.0
        log-level: vv
        manifest-path: pyproject.toml
        # cache: true
        # auth-host: prefix.dev
        # auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

    - name: Run Pixi
      run: |
        pixi run python --version | grep 3.12
        pixi run test | grep -q "Hello world"

  Semantic-Release:
    runs-on: ubuntu-latest
    needs: Run-A-Pixi-Job
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        root_options: -v
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: 'gh-actions-semver'