name: Semantic Release

on:
  push:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]
  pull_request:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]

jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        root_options: -v
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: 'gh-actions-semver'