name: Semantic Release


# only run on pushes to main or pull requests
on:
  push:
    branches: [ main , (dev|development) , (stg|staging) ]
  pull_request:
    branches: [ main , (dev|development) , (stg|staging) ]

jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        root_options: -v
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: 'gh-actions-semver'