name: Semantic Release

on:
  push:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]
  pull_request:
    branches: [ 'main' , 'dev' , 'development' , 'staging', 'stg' ]

jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        root_options: -v
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: 'gh-actions-semver'

  Run-A-Pixi-Job:
    runs-on: ubuntu-latest
    needs: Semantic-Release
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run A Pixi Job
      run: echo "Running a Pixi Job"

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.18.0
        cache: true
        auth-host: prefix.dev
        auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

    - name: Pixi Info
      run: pixi info    

    - name: Run a command in pixi
      run: |
        import src 
        print(src.__version__)